include_guard()

find_package(Git REQUIRED)

include(FetchContent)
FetchContent_Declare(TBB
    GIT_REPOSITORY "https://github.com/oneapi-src/oneTBB.git"
    GIT_TAG "1c4c93fc5398c4a1acb3492c02db4699f3048dea" # 2021.13.0
    GIT_SHALLOW ON
    GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
    CMAKE_ARGS "-DTBB_STRICT:BOOL=OFF
                -DTBB_TEST:BOOL=OFF
                -DTBB_EXAMPLES:BOOL=OFF
                -DTBB_BENCH:BOOL=OFF
                -DTBB_BUILD:BOOL=ON
                -DTBB_FIND_PACKAGE:BOOL=OFF
                -DTBB_FUZZ_TESTING:BOOL=OFF
                -DTBB_INSTALL:BOOL=ON"
    FIND_PACKAGE_ARGS 2021.13 CONFIG
)

set(TBB_STRICT OFF CACHE INTERNAL "" FORCE)
set(TBB_TEST OFF CACHE INTERNAL "" FORCE)
set(TBB_EXAMPLES OFF CACHE INTERNAL "" FORCE)
set(TBB_BENCH OFF CACHE INTERNAL "" FORCE)
set(TBB_BUILD ON CACHE INTERNAL "" FORCE)
set(TBB_FIND_PACKAGE OFF CACHE INTERNAL "" FORCE)
set(TBB_FUZZ_TESTING OFF CACHE INTERNAL "" FORCE)
set(TBB_INSTALL ON CACHE INTERNAL "" FORCE)

if (EMSCRIPTEN)
    set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} -Wno-unused-command-line-argument)
    set(TBB_DISABLE_HWLOC_AUTOMATIC_SEARCH ON CACHE INTERNAL "" FORCE)
    set(EMSCRIPTEN_WITHOUT_PTHREAD OFF CACHE INTERNAL "" FORCE)
endif()

FetchContent_MakeAvailable(TBB)
if (NOT TARGET TBB::tbb)
    message(FATAL_ERROR "TBB setup failed")
endif()
message(STATUS "TBB added")